before_script: - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY


deploy:
  script:
    - export TAG="${CI_BUILD_REF_NAME}"
    - docker stack deploy -c docker-compose.yml writer
  stage: deploy
  tags:
    - shell
  only:
    - tags
    - triggers


stages:
  - deploy
