version: "3.4"

services:
  consul:
    command: 'agent -server -ui -client=0.0.0.0 -bootstrap-expect 1'
    image: 'consul'
    ports:
      - 8500:8500
    networks:
      - consul
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
      - CONSUL_BIND_INTERFACE=eth0

    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
          cpus: '0.2'
      restart_policy:
        condition: on-failure

networks:
  consul:
    external: true
